# Try-Finally
ITSE 1430 
:toc:

The https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally[try-finally] block is used to execute code when leaving a block, under any circumstances. 

When working with code it is often necessary to clean up an object when you are done with it. Care must be taken to ensure the resource is cleaned up even in cases of link:../error-handling/exceptions.adoc[exceptions].

.Unsafe Resource Cleanup
```csharp
try
{
   var resource = GetSharedResource();
   //Do work

   FreeResource(resource);
} catch 
{   
};
```

## Exception Safe Clean Up

This code is not "exception-safe" (safe to run even when an exception occurs). If an error occurs after the resource is allocated but before it is freed then the line containing the cleanup method will never run and we have a resource leak. To fix this we need to ensure the resource is cleaned up in both cases.

.Safe Resource Cleanup
```csharp
IResource resource = null;
try
{
   resource = GetSharedResource();
   //Do work

   FreeResource(resource);
} catch 
{   
   //Handle error
   if (resource != null)
      FreeResource(resource);
};
```

For a single method call this is OK but if the cleanup requires more code then we are repeating ourselves which is bad. Even worse is that this is still not exception safe. If the code in the `finally` block throws an exception then the resource is not going to cleaned up.

## Try-Finally Block

The https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally[try-finally] block is designed for this situation. A `finally` block executes after the `try` block to allow the code to clean up any resources. A `finally` block is always guaranteed to execute irrelevant of whether the code completes successfully or not. This guarantee makes clean up exception safe.

.Using a Try-Finally Block
```csharp
IResource resource = null;
try
{
   resource = GetSharedResource();
   //Do work   
} finally
{
   if (resource != null)  
      FreeResource(resource);
};
```

Notice in this code we needed to hoist the `resource` variable outside the `try` block so it could be accessed in the `finally` block. We also need to ensure that the variable is valid before we use it. Code in the `finally` block should make no assumption that any code has executed before it runs. Lastly, just like the `catch` block, ensure the code in the `finally` block is resilient. Any error in this code is just like an error in a `catch` block. 

NOTE: If an exception occurs then the `finally` block is executed just before the current stack frame is cleaned up. 

## Try-Catch-Finally Block

In some cases code might want to handle exceptions using a `try-catch` and still use a `finally` to clean up code. The `try-catch` block may include a `finally` block in this case. The `finally` block must be last and there can be only one.

.Using a Try-Catch-Finally Block
```csharp
IResource resource = null;
try
{
   resource = GetSharedResource();
   //Do work   
} catch 
{   
   //Handle error  
} finally
{
   if (resource != null)  
      FreeResource(resource);
};
```

`finally` blocks are executed after either the `try` or `catch` block executes to completion. If no `catch` block executes (or fails) then the `finally` block is still executed.

## See Also

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally[C# Try-Finally] +
link:try-catch.adoc[Try-Catch] +
link:using-statement.adoc[Using Statement]